package raillylinker.module_idp_jpa.data_sources.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import raillylinker.module_idp_jpa.data_sources.entities.MiddleLevelSpringbootProject1_ServicePointPaymentTossPayInfo;

@Repository
public interface MiddleLevelSpringbootProject1_ServicePointPaymentTossPayInfoRepository extends JpaRepository<MiddleLevelSpringbootProject1_ServicePointPaymentTossPayInfo, Long> {
//    Optional<MiddleLevelSpringbootProject1_ServicePoint> findByFreelancerAndRowDeleteDateStr(MiddleLevelSpringbootProject1_Freelancer freelancer, String rowDeleteDateStr);
}
