package raillylinker.module_idp_jpa.data_sources.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import raillylinker.module_idp_jpa.data_sources.entities.MiddleLevelSpringbootProject1_Freelancer;
import raillylinker.module_idp_jpa.data_sources.entities.MiddleLevelSpringbootProject1_FreelancerView;

import java.util.Optional;

@Repository
public interface MiddleLevelSpringbootProject1_FreelancerViewRepository extends JpaRepository<MiddleLevelSpringbootProject1_FreelancerView, Long> {
    Optional<MiddleLevelSpringbootProject1_FreelancerView> findByFreelancerAndRowDeleteDateStr(MiddleLevelSpringbootProject1_Freelancer freelancer, String rowDeleteDateStr);
}
